# Generated by Django 6.0.2 on 2026-03-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='github_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
