# Generated by Django 6.0.2 on 2026-03-30 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_management', '0002_pullrequest_github_created_at_pullrequest_merged_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('merged', 'Merged'), ('rejected', 'Rejected')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('github_event_id', models.BigIntegerField(blank=True, null=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='projects_management.pullrequest')),
            ],
            options={
                'verbose_name_plural': 'Pull Request Status Histories',
                'ordering': ['changed_at'],
            },
        ),
    ]
