# Generated by Django 6.0.2 on 2026-03-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_management', '0003_pullrequeststatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequeststatushistory',
            name='changed_at',
            field=models.DateTimeField(),
        ),
    ]
