# Generated by Django 5.2.9 on 2026-02-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Certificate name or domain', max_length=200)),
                ('domain', models.CharField(help_text='Primary domain', max_length=255)),
                ('alternative_names', models.JSONField(default=list, help_text='SAN domains')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('key_type', models.CharField(choices=[('RSA', 'RSA'), ('ECDSA', 'ECDSA'), ('DSA', 'DSA'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('issuer', models.CharField(blank=True, max_length=500, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('cert_path', models.CharField(blank=True, help_text='Path to certificate file', max_length=500, null=True)),
                ('key_path', models.CharField(blank=True, help_text='Path to private key file', max_length=500, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False, help_text='Certificate is currently valid')),
                ('is_self_signed', models.BooleanField(default=False)),
                ('days_until_expiry', models.IntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('check_frequency', models.IntegerField(default=24, help_text='Check frequency in hours')),
                ('warning_days', models.IntegerField(default=30, help_text='Days before expiry to send warning')),
                ('critical_days', models.IntegerField(default=7, help_text='Days before expiry to send critical alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SSL Certificate',
                'verbose_name_plural': 'SSL Certificates',
                'ordering': ['expires_at'],
                'indexes': [models.Index(fields=['enabled', 'expires_at'], name='monitor_ssl_enabled_364717_idx'), models.Index(fields=['domain'], name='monitor_ssl_domain_d80598_idx')],
            },
        ),
    ]
