# Generated by Django 5.2.9 on 2026-02-03 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_sslcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertevent',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='monitor.server'),
        ),
    ]
