# Generated by Django 6.0.2 on 2026-02-19 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_alertevent_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ssl_cert_path',
            field=models.CharField(blank=True, default='', help_text='Path to SSL certificate file on the server (for SSH-based monitoring)', max_length=500),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='server',
            field=models.ForeignKey(blank=True, help_text='Associated server for this certificate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssl_certificates_list', to='monitor.server'),
        ),
    ]
