# Generated by Django 6.0.2 on 2026-02-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_server_ssl_cert_path_sslcertificate_server'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resourcesample',
            index=models.Index(fields=['collected_at'], name='monitor_res_collect_69c89c_idx'),
        ),
    ]
