# Generated by Django 6.0.2 on 2026-02-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_resourcesample_monitor_res_collect_69c89c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='latest_folder_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='latest_folder_files',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='latest_folder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='latest_folder_size_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='watch_directory',
            field=models.CharField(blank=True, default='', help_text='Directory to watch for the latest created folder', max_length=500),
        ),
    ]
