# Generated by Django 6.0.2 on 2026-02-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_server_latest_folder_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='last_status',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Last known status of the device', max_length=10),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='kind',
            field=models.CharField(choices=[('server_down', 'Server down'), ('http_unhealthy', 'HTTP unhealthy'), ('agent_stale', 'Agent stale'), ('db_connect_fail', 'DB connect failed'), ('cpu_high', 'CPU high'), ('ram_high', 'RAM high'), ('db_conn_high', 'DB connection usage high'), ('device_down', 'Network device down')], max_length=50),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='device_type',
            field=models.CharField(choices=[('FIREWALL', 'Firewall'), ('SWITCH', 'Switch'), ('ROUTER', 'Router'), ('PC', 'PC/Computer'), ('MOBILE', 'Mobile Phone'), ('PRINTER', 'Printer'), ('ACCESS_POINT', 'Access Point'), ('NAS', 'NAS/Storage'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
