# Generated by Django 5.2.9 on 2026-03-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_networkdevice_last_status_alter_alertrule_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTRBiometricMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('false_rejection_rate', models.FloatField(help_text='FRR - Valid employees rejected (%)')),
                ('retry_count_avg', models.FloatField(help_text='Avg attempts before successful punch')),
                ('liveness_failures', models.IntegerField(help_text='Spoofing attempts rejected')),
                ('manual_override_rate', models.FloatField(help_text='Supervisor manual interventions (%)')),
                ('recognition_latency', models.FloatField(help_text='Time from shutter to match (ms)')),
                ('app_startup_time', models.FloatField(help_text='App start to camera ready (ms)')),
                ('frame_drop_rate', models.FloatField(help_text='UI jank during face scanning (%)')),
                ('battery_drain_per_punch', models.FloatField(help_text='Battery consumption per punch (%)')),
                ('device_model', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=100)),
                ('geofence_distance', models.FloatField(help_text='Distance from punch zone (meters)')),
                ('sync_lag', models.FloatField(help_text='Local to server sync time (seconds)')),
                ('api_error_rate', models.FloatField(help_text='4XX/5XX error rate (%)')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='monitor_dtr_timesta_059f58_idx'), models.Index(fields=['device_model'], name='monitor_dtr_device__e1b04c_idx'), models.Index(fields=['location_name'], name='monitor_dtr_locatio_1f21cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='DTRDevicePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('successful_sessions', models.IntegerField(default=0)),
                ('failed_sessions', models.IntegerField(default=0)),
                ('avg_recognition_latency', models.FloatField(default=0)),
                ('avg_startup_time', models.FloatField(default=0)),
                ('avg_confidence_score', models.FloatField(default=0)),
                ('avg_attempts', models.FloatField(default=0)),
                ('face_detection_failures', models.IntegerField(default=0)),
                ('liveness_failures', models.IntegerField(default=0)),
                ('network_errors', models.IntegerField(default=0)),
                ('api_errors', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('device_model', 'os_version', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='DTRLocationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('avg_geofence_distance', models.FloatField(default=0)),
                ('lighting_conditions', models.CharField(blank=True, max_length=50)),
                ('network_quality', models.CharField(blank=True, max_length=20)),
                ('total_punches', models.IntegerField(default=0)),
                ('successful_punches', models.IntegerField(default=0)),
                ('avg_recognition_time', models.FloatField(default=0)),
                ('avg_confidence_score', models.FloatField(default=0)),
                ('lighting_issues', models.IntegerField(default=0)),
                ('network_issues', models.IntegerField(default=0)),
                ('geofence_issues', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('location_name', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='DTRPunchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('employee_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('punch_type', models.CharField(max_length=20)),
                ('device_model', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=50)),
                ('app_version', models.CharField(max_length=20)),
                ('startup_time', models.FloatField(blank=True, null=True)),
                ('camera_ready_time', models.FloatField(blank=True, null=True)),
                ('face_detection_time', models.FloatField(blank=True, null=True)),
                ('recognition_time', models.FloatField(blank=True, null=True)),
                ('total_session_time', models.FloatField(blank=True, null=True)),
                ('attempts_count', models.IntegerField(default=1)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('liveness_passed', models.BooleanField(default=True)),
                ('face_detected', models.BooleanField(default=True)),
                ('location_name', models.CharField(blank=True, max_length=100)),
                ('geofence_distance', models.FloatField(blank=True, null=True)),
                ('network_type', models.CharField(blank=True, max_length=20)),
                ('battery_level_before', models.IntegerField(blank=True, null=True)),
                ('battery_level_after', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_type', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('manual_override_required', models.BooleanField(default=False)),
                ('local_timestamp', models.DateTimeField()),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('sync_lag', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee_id', 'timestamp'], name='monitor_dtr_employe_72a1a5_idx'), models.Index(fields=['device_model'], name='monitor_dtr_device__2d31d8_idx'), models.Index(fields=['location_name'], name='monitor_dtr_locatio_e47914_idx'), models.Index(fields=['success'], name='monitor_dtr_success_52d243_idx'), models.Index(fields=['timestamp'], name='monitor_dtr_timesta_daa7c0_idx')],
            },
        ),
    ]
