# Generated by Django 5.2.9 on 2026-03-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_dtr_biometric_monitoring_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtrpunchsession',
            name='local_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
