"""
Django settings for serverwatch project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-31g8r+yrqm&h@0v(t&xuw*63+$###w48u2hyjtqkw@dz+#-n3w'

ENCRYPTION_KEY = 'bb9518544ef4a067dd523e5369680c6553835e5d304a08f51543dd807353f88f' # Generated using secrets.token_hex(32)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["58.69.221.127", "192.168.253.23", "192.168.253.31", "123.253.137.132", "localhost", "127.0.0.1", "0.0.0.0", "*"]

# Also add CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    'http://123.253.137.132:8001',
    'http://192.168.253.23:8001',
    'http://192.168.253.31:8001',
    'http://58.69.221.127:8001',
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'monitor',
    'projects_management',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'monitor.versioning.APIVersioningMiddleware',  # API versioning middleware
    'monitor.versioning.APIVersionDeprecationMiddleware',  # Version deprecation middleware
    # 'monitor.middleware.TokenValidationMiddleware',  # Disabled - let DRF handle auth
    'monitor.middleware.RateLimitMiddleware',  # Re-enabled with higher limits
    'monitor.middleware.SecurityHeadersMiddleware',
    'monitor.middleware.AuditLogMiddleware',
]

SECURE_CROSS_ORIGIN_OPENER_POLICY = None

ROOT_URLCONF = 'serverwatch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'serverwatch.wsgi.application'

ASGI_APPLICATION = 'serverwatch.asgi.application'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutes
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 5,
        }
    },
    # Redis cache for production (uncomment to use)
    # 'redis': {
    #     'BACKEND': 'django_redis.cache.RedisCache',
    #     'LOCATION': 'redis://127.0.0.1:6379/1',
    #     'OPTIONS': {
    #         'CLIENT_CLASS': 'django_redis.client.DefaultClient',
    #         'CONNECTION_POOL_KWARGS': {
    #             'max_connections': 50,
    #             'retry_on_timeout': True,
    #         }
    #     }
    # },
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional static files directories
STATICFILES_DIRS = [
    BASE_DIR / 'monitor' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ServerWatch Configuration
SERVERWATCH_SERVER_HOST = '192.168.253.31'
SERVERWATCH_SERVER_PORT = 8001
SERVERWATCH_SERVER_URL = f'http://{SERVERWATCH_SERVER_HOST}:{SERVERWATCH_SERVER_PORT}'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'TOKEN_EXPIRE_SECONDS': 86400 * 30,  # 30 days
}

# CORS settings for mobile apps
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React Native development
    "http://localhost:19006",  # Expo development
    "http://127.0.0.1:3000",
    "http://127.0.0.1:19006",
]

CORS_ALLOW_ALL_ORIGINS = DEBUG  # Allow all origins in development

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Login URL configuration
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Session configuration
SESSION_COOKIE_AGE = 3600  # 1 hour in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CORS_ALLOW_METHODS = [
#     'delete',
#     'get',
#     'options',
#     'patch',
#     'post',
#     'put',
# ]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CORS settings for API endpoints
CORS_URLS_REGEX = r'^/api/.*$'

# Allow preflight requests for authentication endpoints
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours
